### ISSUE TITLE
Partnership to develop zkEVM layer 2 payments.

### ISSUE THREAD

**Issue by joanseg** [esPass/pretix-espass#6]
Hi there,
Have you considered to support every zkEVM layer 2?
Sprintcheckout.com is a zkEVM payment processor, we would like to partner in order to extend pretix-espass plugin to accept all zkEVM layer 2's.
Please let me know if you would like to have a chat about it? and best way to reach you out.
Many thanks

**Comment by ligi** [comment]
I would be careful with words like `*every*` - but in general supporting more networks is a goal. Can you point me to your code so I can have a look?

**Comment by joanseg** [comment]
Thanks for the prompt reply. We can show you the code on a quick call, please fill free to contact me on https://t.me/joanseg if you prefer. Thanks

**Comment by ligi** [comment]
I do not use telegram - just share the links to the code here

**Comment by joanseg** [comment]
The code is not public at the moment. But you can share the docs here https://docs.sprintcheckout.com/api/overview
We can also show the code and demo the app on a call if you want. Let me know. Cheers.

**Comment by ligi** [comment]
I think it makes most sense to proceed once the code is public.

**Comment by joanseg** [comment]
Sure, no problem, we will come back to you if we make it public.

**Comment by LKS121** [comment]
📚🍔🌙🌟

**Comment by LKS121** [comment]
> Hi there,
> Have you considered to support every zkEVM layer 2?
> Sprintcheckout.com is a zkEVM payment processor, we would like to partner in order to extend pretix-espass plugin to accept all zkEVM layer 2's.
> Please let me know if you would like to have a chat about it? and best way to reach you out.
> Many thanks
> 
I would be careful with words like `*every*` - but in general supporting more networks is a goal. Can you point me to your code so I can have a look?

_Originally posted by @ligi in https://github.com/esPass/pretix-espass/issues/6#issuecomment-1418266007_
